### ISSUE TITLE
Mocking IDocumentDatabase/CouchDatabase

### ISSUE THREAD

**Issue by natery2000** [soitgoes/LoveSeat#72]
I have an application where I would like to mock out the CouchDatabase class. 

I have two options:
- Add the CouchDatabase.Compact function to the IDocumentDatabase interface which is the only function that I require that is not implemented by the interface
- Allow a constructor on the CouchDatabase class to be accessible from outside this assembly so that I can inherit the CouchDatabase class

There might be other solutions, and I would love to hear them.

**Comment by soitgoes** [comment]
You should be able to use Moq with IDocumentDatabase to achieve that

**Comment by natery2000** [comment]
I was not aware of our companies fork of this repository before I created this issue. This issue was fixed over there.
